
$CONFIG->databasePassword = 'XXXX';


$CONFIG->ExtensionWebAPI1StatsDBPassword = "XXXX";

$CONFIG->sysAdminExtraPassword = "XXXXXXXXXXXXXXXXXXXXX";


$CONFIG->SMTPUsername = "BBB";

$CONFIG->SMTPPassword = "HHTTHT";


$CONFIG->TWITTER_APP_APP_KEY = null;
$CONFIG->TWITTER_APP_APP_SECRET = null;
$CONFIG->TWITTER_APP_USER_TOKEN = null;
$CONFIG->TWITTER_APP_USER_SECRET = null;
