DROP TABLE IF EXISTS human_popit_information CASCADE;
DROP TABLE IF EXISTS area_mapit_information CASCADE;
DROP TABLE IF EXISTS human_information CASCADE;
DROP TABLE IF EXISTS human_history  CASCADE;
DROP TABLE IF EXISTS event_has_human CASCADE;
DROP TABLE IF EXISTS human_in_area CASCADE;
DROP TABLE IF EXISTS human_email CASCADE;
